version: "3.8"

services: 
  shlink:
    image: shlinkio/shlink
    restart: always
    container_name: shlink
    ports:
      - 8080:8080
    environment:
      - DEFAULT_DOMAIN=your_domain
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=your_Maxmind_key
      - DB_DRIVER=mysql
      - DB_USER=your_db_username
      - DB_PASSWORD=your_db_password
      - DB_HOST=your_db_host:your_db_port
