version: '3'
services:
    zfile:
        container_name: zfile
        restart: always
        ports:
            - '5008:8080'
        volumes:
            - './db:/root/.zfile-v4/db'
            - './logs:/root/.zfile-v4/logs'
            - './file:/data/file'
        image: zhaojun1998/zfile
