version: '3.8'
services:
  nginx-proxy-manage:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "your_host_ip"
      DB_MYSQL_PORT: your_port
      DB_MYSQL_USER: "your_username"
      DB_MYSQL_PASSWORD: "your_password"
      DB_MYSQL_NAME: "your_database_name"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
