version: "3.8"

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - "8200:80"
    environment:
      YOURLS_DB_HOST: your_db_host:your_db_port
      YOURLS_DB_USER: your_db_username
      YOURLS_DB_PASS: your_db_password
      YOURLS_DB_NAME: your_db_name
      YOURLS_USER: your_username
      YOURLS_PASS: your_login_password
      YOURLS_SITE: your_domain
      YOURLS_HOURS_OFFSET: 8
    container_name: yourls
