version: "3.8"
services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      TZ: Asiz/Shanghai
    ports:
      - "3306:3306"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
